import { expect, test } from "./fixtures";

test.describe.serial("관리자 주요 흐름",()=>{
 let programId="";let versionId="";
 test("비로그인 보호와 잘못된 로그인",async({page})=>{await page.goto("/admin");await expect(page).toHaveURL(/\/admin\/login$/);await page.getByLabel("이메일").fill(process.env.E2E_ADMIN_EMAIL!);await page.getByLabel("비밀번호").fill("incorrect password value");await page.getByRole("button",{name:"로그인"}).click();await expect(page.getByRole("alert")).toBeVisible()});
 test("로그인 후 프로그램 목록에 진입한다",async({page})=>{await page.goto("/admin/login");await page.getByLabel("이메일").fill(process.env.E2E_ADMIN_EMAIL!);await page.getByLabel("비밀번호").fill(process.env.E2E_ADMIN_PASSWORD!);await page.getByRole("button",{name:"로그인"}).click();await expect(page).toHaveURL(/\/admin$/);await page.getByRole("link",{name:"지원제도",exact:true}).click();await expect(page.getByRole("heading",{name:"지원제도"})).toBeVisible()});
 test("새 프로그램과 첫 DRAFT를 생성한다",async({page})=>{await login(page);await page.goto("/admin/programs/new");const slug=`e2e-program-${Date.now()}`;await page.getByLabel("slug (영문 소문자와 하이픈)").fill(slug);await page.getByLabel("관리 기관").fill("부산광역시 E2E 기관");await page.getByLabel("제도명").fill("E2E 청년 지원제도");await page.getByLabel("짧은 설명").fill("E2E 전용 가상 데이터");await page.getByLabel("상세 설명").fill("운영 데이터가 아닌 브라우저 검증용 가상 제도입니다.");await page.getByLabel("대상 요약").fill("부산 청년");await page.getByLabel("지원 형태").fill("서비스");await page.getByLabel("공식 정보 확인일").fill("2026-07-19");await page.getByLabel("신청 방법").fill("온라인");await page.getByLabel("문의처").fill("E2E 담당자");await page.getByRole("button",{name:"DRAFT 생성 후 구성 편집"}).click();await expect(page).toHaveURL(/\/admin\/program-versions\/[^/]+\/edit$/);versionId=page.url().match(/program-versions\/([^/]+)/)![1]!;const detail=await page.request.get(`/api/admin/program-versions/${versionId}`);programId=(await detail.json()).programId});
 test("NATIONAL DRAFT 출처·지역·규칙·테스트 사례를 저장한다",async({page})=>{await login(page);await page.goto(`/admin/program-versions/${versionId}/edit`);await page.getByLabel("문서명").fill("E2E 공식 안내");await page.getByLabel("공식 URL").fill("https://www.busan.go.kr/e2e-test");await page.getByLabel("부산 거주 필수 여부 기준").selectOption("NATIONAL");await expect(page.getByText("신청자의 부산 주민등록이 필수조건이 아닌 제도입니다.")).toBeVisible();await page.getByRole("button",{name:"DRAFT 구성 저장"}).click();await expect(page.getByRole("status")).toContainText("저장했습니다")});
 test("테스트 실행 후 readiness를 확인하고 게시한다",async({page})=>{await login(page);await page.goto(`/admin/program-versions/${versionId}/tests`);await confirmNextDialog(page);await page.getByRole("button",{name:"테스트 실행"}).click();await expect(page.getByText("전체 통과")).toBeVisible();await expect(page.getByText("게시 준비 완료")).toBeVisible();await page.getByLabel("게시 사유").fill("E2E 최초 게시");await confirmNextDialog(page);await page.getByRole("button",{name:"게시 확인"}).click();await expect(page).toHaveURL(new RegExp(`/admin/programs/${programId}$`));await expect(page.getByRole("article").getByText("현재 공개 버전")).toBeVisible()});
 test("현재 공개 버전에서 새 DRAFT를 생성한다",async({page})=>{await login(page);await page.goto(`/admin/programs/${programId}`);await confirmNextDialog(page);await page.getByRole("button",{name:"새 DRAFT 생성"}).click();await expect(page).toHaveURL(/\/admin\/program-versions\/[^/]+\/edit$/);await expect(page.getByRole("heading",{name:/DRAFT v2 편집/})).toBeVisible()});
 test("로그아웃 후 보호 페이지를 차단한다",async({page})=>{await login(page);await page.getByRole("button",{name:"로그아웃"}).click();await expect(page).toHaveURL(/\/admin\/login$/);await page.goto("/admin/programs");await expect(page).toHaveURL(/\/admin\/login$/)});
});

async function login(page:import("@playwright/test").Page){await page.goto("/admin/login");if(page.url().endsWith("/admin"))return;await page.getByLabel("이메일").fill(process.env.E2E_ADMIN_EMAIL!);await page.getByLabel("비밀번호").fill(process.env.E2E_ADMIN_PASSWORD!);await page.getByRole("button",{name:"로그인"}).click();await expect(page).toHaveURL(/\/admin$/)}
function confirmNextDialog(page:import("@playwright/test").Page){page.once("dialog",dialog=>dialog.accept())}
