"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { CreateAdminProgramBodySchema } from "@/features/admin/programs/schemas/admin-program-api.schema";
import type { CreatedProgramResult } from "@/features/admin/programs/types/admin-program.types";
import { adminApi, adminErrorMessage } from "./api-client";
import { AdminPageHeader, BackLink, Panel, fieldClass, primaryButton } from "./admin-ui";

function optional(value: FormDataEntryValue | null): string | null { const text=String(value??"").trim(); return text || null; }

export function AdminProgramCreateForm() {
  const router=useRouter(); const [pending,setPending]=useState(false); const [error,setError]=useState(""); const [applicationType,setApplicationType]=useState("ALWAYS_OPEN"); const [amountType,setAmountType]=useState("UNDETERMINED");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setError("");const form=new FormData(event.currentTarget);const body={program:{slug:String(form.get("slug")??""),category:String(form.get("category")??""),managingOrganization:String(form.get("managingOrganization")??""),operatingOrganization:optional(form.get("operatingOrganization"))},version:{title:String(form.get("title")??""),shortDescription:String(form.get("shortDescription")??""),fullDescription:String(form.get("fullDescription")??""),targetSummary:String(form.get("targetSummary")??""),benefitType:String(form.get("benefitType")??""),amountType,minimumAmount:optional(form.get("minimumAmount")),maximumAmount:optional(form.get("maximumAmount")),amountUnit:optional(form.get("amountUnit")),amountDescription:optional(form.get("amountDescription")),applicationType,applicationStartDate:optional(form.get("applicationStartDate")),applicationEndDate:optional(form.get("applicationEndDate")),applicationMethod:String(form.get("applicationMethod")??""),applicationUrl:optional(form.get("applicationUrl")),contactInformation:String(form.get("contactInformation")??""),requiredDocuments:String(form.get("requiredDocuments")??"").split("\n").map(v=>v.trim()).filter(Boolean),cautionText:optional(form.get("cautionText")),checkedAt:String(form.get("checkedAt")??"")}};const parsed=CreateAdminProgramBodySchema.safeParse(body);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join(" "));return;}setPending(true);try{const created=await adminApi<CreatedProgramResult>("/api/admin/programs",{method:"POST",body:JSON.stringify(parsed.data)});router.push(`/admin/program-versions/${created.initialVersion.id}/edit`);}catch(e){setError(adminErrorMessage(e));}finally{setPending(false)}}
  const input=(name:string,label:string,type="text",required=true)=><label className="grid gap-2 text-sm font-bold" htmlFor={name}>{label}<input className={fieldClass} id={name} name={name} required={required} type={type}/></label>;
  return <div className="space-y-7"><BackLink href="/admin/programs"/><AdminPageHeader title="새 지원제도" description="프로그램 식별 정보와 첫 DRAFT 버전의 기본 내용을 등록합니다."/><form className="space-y-6" onSubmit={submit}>
    <Panel title="프로그램 식별 정보"><div className="grid gap-4 md:grid-cols-2">{input("slug","slug (영문 소문자와 하이픈)")}<label className="grid gap-2 text-sm font-bold">분야<select className={fieldClass} name="category"><option value="YOUTH_EMPLOYMENT">청년 취업</option><option value="YOUTH_HOUSING">청년 주거</option></select></label>{input("managingOrganization","관리 기관")}{input("operatingOrganization","운영 기관","text",false)}</div></Panel>
    <Panel title="기본 설명"><div className="grid gap-4">{input("title","제도명")}{input("shortDescription","짧은 설명")}<label className="grid gap-2 text-sm font-bold">상세 설명<textarea className={fieldClass} name="fullDescription" required rows={5}/></label>{input("targetSummary","대상 요약")}{input("benefitType","지원 형태")}</div></Panel>
    <Panel title="지원 금액"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">금액 유형<select className={fieldClass} name="amountType" onChange={e=>setAmountType(e.target.value)} value={amountType}>{["UNDETERMINED","FIXED","RANGE","MAXIMUM","FORMULA","IN_KIND"].map(v=><option key={v}>{v}</option>)}</select></label>{input("amountUnit","금액 단위","text",false)}{input("minimumAmount","최소/정액 금액","text",false)}{input("maximumAmount","최대 금액","text",false)}{input("amountDescription","금액 설명","text",false)}</div></Panel>
    <Panel title="신청 정보"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold">신청 유형<select className={fieldClass} name="applicationType" onChange={e=>setApplicationType(e.target.value)} value={applicationType}>{["ALWAYS_OPEN","FIXED_PERIOD","BUDGET_EXHAUSTION"].map(v=><option key={v}>{v}</option>)}</select></label>{input("checkedAt","공식 정보 확인일","date")}{input("applicationStartDate","신청 시작일","date",applicationType==="FIXED_PERIOD")}{input("applicationEndDate","신청 종료일","date",applicationType==="FIXED_PERIOD")}{input("applicationMethod","신청 방법")}{input("applicationUrl","공식 신청 URL","url",false)}{input("contactInformation","문의처")}<label className="grid gap-2 text-sm font-bold">필요 서류 (한 줄에 하나)<textarea className={fieldClass} name="requiredDocuments" rows={4}/></label><label className="grid gap-2 text-sm font-bold md:col-span-2">주의사항<textarea className={fieldClass} name="cautionText" rows={3}/></label></div></Panel>
    {error?<p className="rounded-xl bg-red-50 p-4 text-red-800" role="alert">{error}</p>:null}<button className={primaryButton} disabled={pending} type="submit">{pending?"생성 중":"DRAFT 생성 후 구성 편집"}</button>
  </form></div>;
}
