"use client";

import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import type { AdminProgramVersionDetail } from "@/features/admin/programs/types/admin-program-detail.types";
import type { ProgramTestRunResult,PublicationReadinessResult } from "@/features/admin/programs/types/program-test-run.types";
import type { PublishProgramVersionResult } from "@/features/admin/programs/types/program-publication.types";
import { AdminApiError,adminApi,adminErrorMessage } from "./api-client";
import { AdminPageHeader,BackLink,Panel,StatusBadge,fieldClass,primaryButton,secondaryButton } from "./admin-ui";

export function ProgramVersionVerification({versionId}:{versionId:string}){
 const router=useRouter();const [detail,setDetail]=useState<AdminProgramVersionDetail|null>(null);const [readiness,setReadiness]=useState<PublicationReadinessResult|null>(null);const [run,setRun]=useState<ProgramTestRunResult|null>(null);const [reason,setReason]=useState("");const [pending,setPending]=useState<"test"|"publish"|null>(null);const [error,setError]=useState("");
 async function load(){try{const [d,r]=await Promise.all([adminApi<AdminProgramVersionDetail>(`/api/admin/program-versions/${versionId}`),adminApi<PublicationReadinessResult>(`/api/admin/program-versions/${versionId}/publication-readiness`)]);setDetail(d);setReadiness(r)}catch(e){setError(adminErrorMessage(e))}}
 useEffect(()=>{Promise.all([adminApi<AdminProgramVersionDetail>(`/api/admin/program-versions/${versionId}`),adminApi<PublicationReadinessResult>(`/api/admin/program-versions/${versionId}/publication-readiness`)]).then(([d,r])=>{setDetail(d);setReadiness(r)}).catch(e=>setError(adminErrorMessage(e)))},[versionId]);
 async function runTests(){if(pending||!window.confirm("저장된 테스트 사례를 실행할까요?"))return;setPending("test");setError("");try{const result=await adminApi<ProgramTestRunResult>(`/api/admin/program-versions/${versionId}/tests`,{method:"POST",body:"{}"});setRun(result);await load()}catch(e){setError(adminErrorMessage(e))}finally{setPending(null)}}
 async function publish(){if(pending||!readiness?.ready||!reason.trim())return;if(!window.confirm("이 버전을 게시할까요? 기존 공개 버전은 UNPUBLISHED로 전환됩니다."))return;setPending("publish");setError("");try{const result=await adminApi<PublishProgramVersionResult>(`/api/admin/program-versions/${versionId}/publish`,{method:"POST",body:JSON.stringify({reason})});router.push(`/admin/programs/${result.programId}`)}catch(e){setError(e instanceof AdminApiError&&e.status===409?`${adminErrorMessage(e)} 게시 준비 상태를 다시 확인해 주세요.`:adminErrorMessage(e));await load()}finally{setPending(null)}}
 if(error&&!detail)return <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>;if(!detail)return <p>버전 정보를 불러오는 중입니다.</p>;
 return <div className="space-y-7"><BackLink href={`/admin/programs/${detail.programId}`}>프로그램 상세</BackLink><AdminPageHeader title={`v${detail.versionNumber} 검증과 게시`} description={detail.title} action={<StatusBadge status={detail.publicationStatus}/>}/>{error?<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>:null}
 <div className="grid gap-5 lg:grid-cols-2"><Panel title="규칙 테스트 실행"><p className="text-sm text-muted">저장된 가상 사례를 규칙 엔진으로 실행하고 결과를 DB에 기록합니다.</p><button className={`${primaryButton} mt-4`} disabled={pending!==null||detail.publicationStatus!=="DRAFT"} onClick={runTests}>{pending==="test"?"실행 중":"테스트 실행"}</button>{run?<div className="mt-5 rounded-xl bg-zinc-50 p-4"><p className="font-black">{run.overallPassed?"전체 통과":"실패 사례 있음"}</p><p className="text-sm">총 {run.totalCount} · 통과 {run.passedCount} · 실패 {run.failedCount}</p><p className="mt-1 text-xs text-muted">hash {run.configurationHash.slice(0,12)} · {new Date(run.executedAt).toLocaleString("ko-KR")}</p><ul className="mt-3 space-y-2">{run.results.map(item=><li key={item.testCaseId} className="rounded-lg border border-line bg-white p-3 text-sm"><b>{item.name}</b> · 기대 {item.expectedStatus} / 실제 {item.actualStatus}{item.failureReasons.length?<p className="text-red-700">{item.failureReasons.join(" ")}</p>:null}</li>)}</ul></div>:null}</Panel>
 <Panel title="게시 준비 상태">{!readiness?<p>검사 중입니다.</p>:<><p className={`font-black ${readiness.ready?"text-emerald-700":"text-amber-800"}`}>{readiness.ready?"게시 준비 완료":"추가 확인 필요"}</p><ul className="mt-4 space-y-2">{readiness.checks.map(check=><li key={check.code} className="flex gap-2 text-sm"><span aria-hidden>{check.passed?"✓":"✕"}</span><span><b>{check.code}</b><br/><span className="text-muted">{check.message}</span></span></li>)}</ul>{readiness.latestTestRun?<p className="mt-4 text-xs text-muted">최신 실행 {new Date(readiness.latestTestRun.executedAt).toLocaleString("ko-KR")} · hash {readiness.latestTestRun.configurationHash.slice(0,12)}</p>:null}</>}</Panel></div>
 <Panel title="게시"><p className="text-sm leading-6 text-muted">서버 readiness가 준비 완료인 경우에만 게시할 수 있습니다. 버튼 상태와 무관하게 서버가 모든 조건을 다시 검사합니다.</p><label className="mt-4 grid gap-2 text-sm font-bold">게시 사유<input className={fieldClass} maxLength={500} onChange={e=>setReason(e.target.value)} value={reason}/></label><div className="mt-4 flex gap-3"><button className={primaryButton} disabled={!readiness?.ready||!reason.trim()||pending!==null||detail.publicationStatus!=="DRAFT"} onClick={publish}>{pending==="publish"?"게시 중":"게시 확인"}</button><button className={secondaryButton} onClick={()=>void load()} type="button">상태 새로고침</button></div></Panel></div>;
}
