export const domainErrorCodes = [
  "VALIDATION_ERROR",
  "ADMIN_NOT_FOUND",
  "ADMIN_INACTIVE",
  "ADMIN_EMAIL_CONFLICT",
  "PROGRAM_NOT_FOUND",
  "PROGRAM_SLUG_CONFLICT",
  "PROGRAM_VERSION_NOT_FOUND",
  "PROGRAM_VERSION_NOT_EDITABLE",
  "PROGRAM_ARCHIVED",
  "PROGRAM_VERSION_NOT_PUBLISHABLE",
  "PROGRAM_VERSION_ALREADY_PUBLISHED",
  "PUBLICATION_READINESS_FAILED",
  "TEST_CONFIGURATION_OUTDATED",
  "CURRENT_PUBLISHED_VERSION_CONFLICT",
  "DRAFT_VERSION_ALREADY_EXISTS",
  "VERSION_NUMBER_CONFLICT",
  "SOURCE_VERSION_NOT_IN_PROGRAM",
  "TRANSACTION_CONFLICT",
  "PRIMARY_SOURCE_REQUIRED",
  "MULTIPLE_PRIMARY_SOURCES",
  "REGION_CONFLICT",
  "RULE_SOURCE_REFERENCE_INVALID",
  "TEST_RULE_REFERENCE_INVALID",
  "PROGRAM_VERSION_NOT_TESTABLE",
  "NO_ACTIVE_RULES",
  "NO_TEST_CASES",
  "NO_REQUIRED_TEST_CASES",
  "RULE_CONFIGURATION_INVALID",
  "TEST_INPUT_INVALID",
  "TEST_EXECUTION_FAILED",
  "AUTHENTICATION_FAILED",
  "SESSION_INVALID",
  "CSRF_VALIDATION_FAILED",
  "LOGIN_RATE_LIMITED",
  "DATABASE_UNAVAILABLE",
  "DATABASE_CONSTRAINT_ERROR",
  "INTERNAL_ERROR",
] as const;

export type DomainErrorCode = (typeof domainErrorCodes)[number];

export class DomainError extends Error {
  constructor(
    public readonly code: DomainErrorCode,
    message: string,
    public readonly details?: unknown,
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = "DomainError";
  }
}

export function getDomainErrorHttpStatus(code: DomainErrorCode): number {
  switch (code) {
    case "VALIDATION_ERROR":
      return 400;
    case "AUTHENTICATION_FAILED":
    case "SESSION_INVALID":
      return 401;
    case "CSRF_VALIDATION_FAILED":
      return 403;
    case "LOGIN_RATE_LIMITED":
      return 429;
    case "ADMIN_NOT_FOUND":
    case "PROGRAM_NOT_FOUND":
    case "PROGRAM_VERSION_NOT_FOUND":
      return 404;
    case "ADMIN_INACTIVE":
    case "ADMIN_EMAIL_CONFLICT":
    case "PROGRAM_SLUG_CONFLICT":
    case "PROGRAM_VERSION_NOT_EDITABLE":
    case "PROGRAM_ARCHIVED":
    case "PROGRAM_VERSION_NOT_PUBLISHABLE":
    case "PROGRAM_VERSION_ALREADY_PUBLISHED":
    case "PUBLICATION_READINESS_FAILED":
    case "TEST_CONFIGURATION_OUTDATED":
    case "CURRENT_PUBLISHED_VERSION_CONFLICT":
    case "DRAFT_VERSION_ALREADY_EXISTS":
    case "VERSION_NUMBER_CONFLICT":
    case "SOURCE_VERSION_NOT_IN_PROGRAM":
    case "TRANSACTION_CONFLICT":
    case "PRIMARY_SOURCE_REQUIRED":
    case "MULTIPLE_PRIMARY_SOURCES":
    case "REGION_CONFLICT":
    case "RULE_SOURCE_REFERENCE_INVALID":
    case "TEST_RULE_REFERENCE_INVALID":
    case "PROGRAM_VERSION_NOT_TESTABLE":
    case "NO_ACTIVE_RULES":
    case "NO_TEST_CASES":
    case "NO_REQUIRED_TEST_CASES":
    case "RULE_CONFIGURATION_INVALID":
    case "TEST_INPUT_INVALID":
    case "TEST_EXECUTION_FAILED":
    case "DATABASE_CONSTRAINT_ERROR":
      return 409;
    case "DATABASE_UNAVAILABLE":
      return 503;
    case "INTERNAL_ERROR":
      return 500;
  }
}
